# Generated by Django 4.2 on 2023-04-29 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
